const { Report, Office, User, Role } = require('../models');
const { addReportJob } = require('../queues/reportQueue');
const moment = require('moment');
const fs = require('fs');
const path = require('path');

module.exports = {
  index: async (request, reply) => {
    try {
      const { page = 1, limit = 15 } = request.query;
      const pageNum = Math.max(1, parseInt(page));
      const limitNum = Math.max(1, parseInt(limit));
      const offset = (pageNum - 1) * limitNum;

      const user = await User.findByPk(request.user.id, {
        include: [
          { model: Office, as: 'Offices' },
          { model: Role, as: 'Roles', through: { attributes: [] } }
        ]
      });

      const roles = user && user.Roles ? user.Roles.map(r => r.name) : [];
      const isAdmin = roles.includes('Admin');

      let availableOffices = [];
      if (isAdmin) {
        availableOffices = await Office.findAll({ attributes: ['id', 'name'], order: [['name', 'ASC']] });
      } else {
        availableOffices = user ? user.Offices : [];
      }

      const { count, rows } = await Report.findAndCountAll({
        where: isAdmin ? {} : { user_id: request.user.id },
        order: [['id', 'DESC']],
        limit: limitNum,
        offset: offset
      });

      const totalPages = Math.ceil(count / limitNum);

      return {
        status: 'success',
        data: rows,
        offices: availableOffices,
        pagination: {
          total: count,
          page: pageNum,
          limit: limitNum,
          totalPages: totalPages,
          hasNextPage: pageNum < totalPages,
          hasPrevPage: pageNum > 1
        }
      };
    } catch (error) {
      return reply.code(500).send({ status: 'error', message: error.message });
    }
  },

  store: async (request, reply) => {
    try {
      const { office_id, fromDate, toDate } = request.body;

      if (!office_id || !fromDate || !toDate) {
        return reply.code(400).send({ status: 'error', message: 'Office, fromDate, and toDate are required' });
      }

      const start = moment(fromDate, 'YYYY-MM-DD');
      const end = moment(toDate, 'YYYY-MM-DD');

      if (!start.isValid() || !end.isValid()) {
        return reply.code(400).send({ status: 'error', message: 'Invalid date format' });
      }

      if (end.diff(start, 'days') > 90) {
        return reply.code(400).send({ status: 'error', message: 'Maximum date range is 90 days' });
      }

      const office = await Office.findByPk(office_id);
      if (!office) {
        return reply.code(404).send({ status: 'error', message: 'Office not found' });
      }

      const user = await User.findByPk(request.user.id);

      // Create Report DB record initialized with 'Processing' status
      const reportRecord = await Report.create({
        title: `Report Generated by ${user ? user.full_name : 'User'}`,
        description: `Attendance Report for ${office.name} from ${fromDate} to ${toDate}`,
        path: 'pending',
        status: 'Processing',
        user_id: request.user.id
      });

      // Dispatch BullMQ background job
      await addReportJob({
        reportId: reportRecord.id,
        officeId: office.id,
        fromDate,
        toDate,
        userId: request.user.id
      });

      return {
        status: 'success',
        message: 'Report Generation is queued. Please refresh after a moment.',
        data: reportRecord
      };
    } catch (error) {
      return reply.code(500).send({ status: 'error', message: error.message });
    }
  },

  download: async (request, reply) => {
    try {
      const { id } = request.params;
      const report = await Report.findByPk(id);
      if (!report) {
        return reply.code(404).send({ status: 'error', message: 'Report not found' });
      }

      if (report.status === 'Processing' || report.path === 'pending') {
        return reply.code(400).send({ status: 'error', message: 'Report generation is still in progress. Please refresh and try again shortly.' });
      }

      if (report.status === 'Failed') {
        return reply.code(500).send({ status: 'error', message: 'Report generation failed. Please regenerate.' });
      }

      const fileName = path.basename(report.path);
      const filePath = path.join(__dirname, '../uploads/reports', fileName);

      if (!fs.existsSync(filePath)) {
        return reply.code(404).send({ status: 'error', message: 'Report file not found on server. It may have been deleted.' });
      }

      // Use a human-readable download filename derived from report description
      const safeTitle = report.title
        ? report.title.replace(/[^a-z0-9_\- ]/gi, '').replace(/\s+/g, '_').slice(0, 60)
        : `report_${id}`;
      const downloadName = `${safeTitle}.xlsx`;

      const fileStream = fs.createReadStream(filePath);
      reply.header('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      reply.header('Content-Disposition', `attachment; filename="${downloadName}"`);
      return reply.send(fileStream);
    } catch (error) {
      return reply.code(500).send({ status: 'error', message: error.message });
    }
  },

  destroy: async (request, reply) => {
    try {
      const { id } = request.params;
      const report = await Report.findByPk(id);
      if (!report) {
        return reply.code(404).send({ status: 'error', message: 'Report not found' });
      }

      if (report.path && report.path !== 'pending') {
        const fileName = path.basename(report.path);
        const filePath = path.join(__dirname, '../uploads/reports', fileName);

        if (fs.existsSync(filePath)) {
          fs.unlinkSync(filePath);
        }
      }

      await report.destroy();
      return { status: 'success', message: 'Report deleted successfully' };
    } catch (error) {
      return reply.code(500).send({ status: 'error', message: error.message });
    }
  }
};
